// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type GtpXdpFwdRule struct {
	Action     uint32
	OutIfindex uint32
	Dmac       [6]uint8
	Smac       [6]uint8
	TeidOut    uint32
	DstIp      uint32
	SrcIp      uint32
	DstPort    uint16
	Pad        [6]uint8
	PktCount   uint64
	ByteCount  uint64
}

type GtpXdpGlobalStats struct {
	Packets uint64
	Bytes   uint64
}

// LoadGtpXdp returns the embedded CollectionSpec for GtpXdp.
func LoadGtpXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GtpXdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GtpXdp: %w", err)
	}

	return spec, err
}

// LoadGtpXdpObjects loads GtpXdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GtpXdpObjects
//	*GtpXdpPrograms
//	*GtpXdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGtpXdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGtpXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GtpXdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpXdpSpecs struct {
	GtpXdpProgramSpecs
	GtpXdpMapSpecs
}

// GtpXdpSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpXdpProgramSpecs struct {
	XdpGtpRouter *ebpf.ProgramSpec `ebpf:"xdp_gtp_router"`
}

// GtpXdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GtpXdpMapSpecs struct {
	StatsMap *ebpf.MapSpec `ebpf:"stats_map"`
	TeidMap  *ebpf.MapSpec `ebpf:"teid_map"`
	UeipMap  *ebpf.MapSpec `ebpf:"ueip_map"`
}

// GtpXdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGtpXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpXdpObjects struct {
	GtpXdpPrograms
	GtpXdpMaps
}

func (o *GtpXdpObjects) Close() error {
	return _GtpXdpClose(
		&o.GtpXdpPrograms,
		&o.GtpXdpMaps,
	)
}

// GtpXdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGtpXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpXdpMaps struct {
	StatsMap *ebpf.Map `ebpf:"stats_map"`
	TeidMap  *ebpf.Map `ebpf:"teid_map"`
	UeipMap  *ebpf.Map `ebpf:"ueip_map"`
}

func (m *GtpXdpMaps) Close() error {
	return _GtpXdpClose(
		m.StatsMap,
		m.TeidMap,
		m.UeipMap,
	)
}

// GtpXdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGtpXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type GtpXdpPrograms struct {
	XdpGtpRouter *ebpf.Program `ebpf:"xdp_gtp_router"`
}

func (p *GtpXdpPrograms) Close() error {
	return _GtpXdpClose(
		p.XdpGtpRouter,
	)
}

func _GtpXdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gtpxdp_bpfel.o
var _GtpXdpBytes []byte
