// Package loader attaches the XDP program to a NIC and pins the BPF maps
// to /sys/fs/bpf/gtp_router/ so CLI commands can access them after this
// process exits. Uses types generated by bpf2go (run: make generate).
package loader

import (
	"fmt"
	"net"
	"os"

	"github.com/cilium/ebpf/link"

	"github.com/gtp-router/control/maps"
)

type Loader struct {
	objs GtpXdpObjects
	xdp  link.Link
	xdpDL link.Link
	iface *net.Interface
}

// Load loads the embedded BPF program, attaches it to uplinkIface (and
// optionally dlIface for the downlink direction), and pins all maps and XDP
// links to the BPF filesystem.
//
// dlIface may be "" to skip the downlink attachment.  dlMode is ignored when
// dlIface is empty.
func Load(uplinkIface string, uplinkMode link.XDPAttachFlags,
	dlIface string, dlMode link.XDPAttachFlags) (*Loader, error) {

	iface, err := net.InterfaceByName(uplinkIface)
	if err != nil {
		return nil, fmt.Errorf("interface %q: %w", uplinkIface, err)
	}

	var objs GtpXdpObjects
	if err := LoadGtpXdpObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("load BPF objects: %w", err)
	}

	if err := os.MkdirAll(maps.PinDir, 0700); err != nil {
		objs.Close()
		return nil, fmt.Errorf("mkdir %s: %w", maps.PinDir, err)
	}

	pins := []struct {
		path string
		pin  func(string) error
	}{
		{maps.PinTeidMap,  objs.TeidMap.Pin},
		{maps.PinUeipMap,  objs.UeipMap.Pin},
		{maps.PinNatMap,   objs.NatMap.Pin},
		{maps.PinStatsMap, objs.StatsMap.Pin},
		{maps.PinTxPort,   objs.TxPort.Pin},
	}
	for _, p := range pins {
		_ = os.Remove(p.path)
		if err := p.pin(p.path); err != nil {
			objs.Close()
			return nil, fmt.Errorf("pin %s: %w", p.path, err)
		}
	}

	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpGtpRouter,
		Interface: iface.Index,
		Flags:     uplinkMode,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach XDP to %s: %w", uplinkIface, err)
	}

	_ = os.Remove(maps.PinProg)
	if err := xdpLink.Pin(maps.PinProg); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not pin uplink XDP link: %v\n", err)
	}

	fmt.Printf("[loader] attached to %s (ifindex=%d, mode=%v)\n", uplinkIface, iface.Index, uplinkMode)

	// Provision the devmap for this interface: downlink rules redirect frames
	// back out the uplink iface (GTP-U encap toward the gNB), so its ifindex
	// must be a valid bpf_redirect_map() target.
	txp := maps.NewTxPortMap(objs.TxPort)
	if err := txp.Ensure(uint32(iface.Index)); err != nil {
		_ = xdpLink.Unpin()
		xdpLink.Close()
		objs.Close()
		return nil, fmt.Errorf("tx_port provision %s: %w", uplinkIface, err)
	}

	l := &Loader{objs: objs, xdp: xdpLink, iface: iface}

	if dlIface != "" {
		// On any failure from here on, unpin the uplink link before closing:
		// the pin would otherwise keep the program attached after this process
		// exits, and every retry would fail with "device or resource busy".
		cleanup := func() {
			_ = xdpLink.Unpin()
			l.Close()
		}
		dlIf, err := net.InterfaceByName(dlIface)
		if err != nil {
			cleanup()
			return nil, fmt.Errorf("downlink interface %q: %w", dlIface, err)
		}
		// Uplink rules redirect decapped frames out the downlink iface (to the
		// internet), so its ifindex must be a valid redirect target. Provision
		// it before attaching so this failure path can't leak a pinned link.
		if err := txp.Ensure(uint32(dlIf.Index)); err != nil {
			cleanup()
			return nil, fmt.Errorf("tx_port provision %s: %w", dlIface, err)
		}
		xdpDL, err := link.AttachXDP(link.XDPOptions{
			Program:   objs.XdpGtpRouter,
			Interface: dlIf.Index,
			Flags:     dlMode,
		})
		if err != nil {
			cleanup()
			return nil, fmt.Errorf("attach XDP to downlink %s: %w", dlIface, err)
		}
		_ = os.Remove(maps.PinProgDownlink)
		if err := xdpDL.Pin(maps.PinProgDownlink); err != nil {
			fmt.Fprintf(os.Stderr, "warning: could not pin downlink XDP link: %v\n", err)
		}
		l.xdpDL = xdpDL
		fmt.Printf("[loader] attached to downlink %s (ifindex=%d, mode=%v)\n", dlIface, dlIf.Index, dlMode)
	}

	fmt.Printf("[loader] maps pinned under %s\n", maps.PinDir)
	return l, nil
}

// Unload detaches XDP programs and removes all BPF filesystem pins.
func Unload(ifaceName string) error {
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return fmt.Errorf("interface %q: %w", ifaceName, err)
	}

	if pinnedLink, err := link.LoadPinnedLink(maps.PinProg, nil); err == nil {
		pinnedLink.Close()
	}
	if pinnedLink, err := link.LoadPinnedLink(maps.PinProgDownlink, nil); err == nil {
		pinnedLink.Close()
	}

	for _, p := range []string{
		maps.PinTeidMap, maps.PinUeipMap, maps.PinNatMap,
		maps.PinStatsMap, maps.PinTxPort, maps.PinProg, maps.PinProgDownlink,
	} {
		_ = os.Remove(p)
	}
	_ = os.Remove(maps.PinDir)

	fmt.Printf("[loader] detached from %s (ifindex=%d)\n", ifaceName, iface.Index)
	return nil
}

func (l *Loader) Close() {
	if l.xdpDL != nil {
		l.xdpDL.Close()
	}
	if l.xdp != nil {
		l.xdp.Close()
	}
	l.objs.Close()
}

func (l *Loader) TeidMap() *maps.TeidMap { return maps.NewTeidMap(l.objs.TeidMap) }
func (l *Loader) UeipMap() *maps.UeipMap { return maps.NewUeipMap(l.objs.UeipMap) }
func (l *Loader) NatMap() *maps.NatMap   { return maps.NewNatMap(l.objs.NatMap) }
