// Package loader attaches the XDP program to a NIC and pins the BPF maps
// to /sys/fs/bpf/gtp_router/ so CLI commands can access them after this
// process exits. Uses types generated by bpf2go (run: make generate).
package loader

import (
	"fmt"
	"net"
	"os"

	"github.com/cilium/ebpf/link"

	"github.com/gtp-router/control/maps"
)

type Loader struct {
	objs  GtpXdpObjects
	xdp   link.Link
	iface *net.Interface
}

// Load loads the embedded BPF program, attaches it to ifaceName via XDP,
// and pins all maps and the XDP link to the BPF filesystem.
func Load(ifaceName string, xdpMode link.XDPAttachFlags) (*Loader, error) {
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return nil, fmt.Errorf("interface %q: %w", ifaceName, err)
	}

	// LoadGtpXdpObjects is generated by bpf2go. It submits the embedded
	// BPF program to the kernel verifier and returns live map/program handles.
	var objs GtpXdpObjects
	if err := LoadGtpXdpObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("load BPF objects: %w", err)
	}

	if err := os.MkdirAll(maps.PinDir, 0700); err != nil {
		objs.Close()
		return nil, fmt.Errorf("mkdir %s: %w", maps.PinDir, err)
	}

	pins := []struct {
		path string
		pin  func(string) error
	}{
		{maps.PinTeidMap,  objs.TeidMap.Pin},
		{maps.PinUeipMap,  objs.UeipMap.Pin},
		{maps.PinStatsMap, objs.StatsMap.Pin},
	}
	for _, p := range pins {
		_ = os.Remove(p.path)
		if err := p.pin(p.path); err != nil {
			objs.Close()
			return nil, fmt.Errorf("pin %s: %w", p.path, err)
		}
	}

	xdpLink, err := link.AttachXDP(link.XDPOptions{
		Program:   objs.XdpGtpRouter,
		Interface: iface.Index,
		Flags:     xdpMode,
	})
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attach XDP to %s: %w", ifaceName, err)
	}

	// Pin the XDP link so the program stays attached after this process exits.
	_ = os.Remove(maps.PinProg)
	if err := xdpLink.Pin(maps.PinProg); err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not pin XDP link: %v\n", err)
	}

	fmt.Printf("[loader] attached to %s (ifindex=%d, mode=%v)\n", ifaceName, iface.Index, xdpMode)
	fmt.Printf("[loader] maps pinned under %s\n", maps.PinDir)

	return &Loader{objs: objs, xdp: xdpLink, iface: iface}, nil
}

// Unload detaches the XDP program and removes all BPF filesystem pins.
func Unload(ifaceName string) error {
	iface, err := net.InterfaceByName(ifaceName)
	if err != nil {
		return fmt.Errorf("interface %q: %w", ifaceName, err)
	}

	if pinnedLink, err := link.LoadPinnedLink(maps.PinProg, nil); err == nil {
		pinnedLink.Close()
	}

	for _, p := range []string{maps.PinTeidMap, maps.PinUeipMap, maps.PinStatsMap, maps.PinProg} {
		_ = os.Remove(p)
	}
	_ = os.Remove(maps.PinDir)

	fmt.Printf("[loader] detached from %s (ifindex=%d)\n", ifaceName, iface.Index)
	return nil
}

func (l *Loader) Close() {
	if l.xdp != nil {
		l.xdp.Close()
	}
	l.objs.Close()
}

func (l *Loader) TeidMap() *maps.TeidMap { return maps.NewTeidMap(l.objs.TeidMap) }
func (l *Loader) UeipMap() *maps.UeipMap { return maps.NewUeipMap(l.objs.UeipMap) }